### ISSUE TITLE
Add ability to open gzip'd bismark cytosine files to "read.bismark"

### ISSUE THREAD

**Issue by timp0** [kasperdanielhansen/bsseq#3]
Would be helpful to keep file size low.

**Comment by kasperdanielhansen** [comment]
This was caused by a switch from scan() to data.table::fread().  The later function is much faster but does not support gzipped files.  Pete has just committed a fix yesterday (which only support gzip I think), and we might switch from data.table::fread() to readr::read_tsv() even though it is slower because this other function has full support for compressed files.
