### ISSUE TITLE
DMRs analyses with bsseq comparing three different populations

### ISSUE THREAD

**Issue by BegonaMartinez** [kasperdanielhansen/bsseq#36]
Hi,

I have WGBS for three different groups of two non-model species (four individuals per group). One is a population of species A and the others are two populations of species B (representing the two extremes of the geographic distribution, 10,000 Km apart). Species A and B are very closely related. I have done a search and have seen that Bsseq is mainly used to do analyses for case-control studies (thus comparing two samples) and not to compare three groups. Could I analyse DMRs among the three populations using bsseq? How?

And a second question. I would like to compare also between species A (four individuals) and species B (eight individuals). Could I do that? (considering the different number of individuals) How?

Thanks a lot in advance. 

All the best,

Begoña Martínez

**Comment by kasperdanielhansen** [comment]
We are in the process of implementing this using the `BSmooth.fstat()` function, which is still in development. This is not documented nor supported at the moment, so its going to be an uphill battle for the next month or two. You could start by using the two-group comparisons in `BSmooth.tstat()`; this should get you most of the way quickly.

For cross-species comparisons we have done work suggesting that you may encounter severe bias caused by mapping; you will need to think about this very carefully.  We are writing on a preprint detailing our observations.
